### ISSUE TITLE
Grade Tiers give incorrect value

### ISSUE THREAD

**Issue by JoseVarelaP** [JoseVarelaP/In-The-Groove2-SM5#3]
This is a mayor problem that i can't seem to know why exactly is doing it.

todo: fill data with explanation

**Comment by StefanoFiumara** [comment]
In other ITG themes, this happens when Percentage Scoring is disabled in metrics.

Could this be a similar issue?

**Comment by JoseVarelaP** [comment]
> In other ITG themes, this happens when Percentage Scoring is disabled in metrics.
> 
> Could this be a similar issue?

It can actually be. dbk2 has told me about this same behavior, StepMania handles scores differently depending of the 2 scoring modes, and thus gives different variables.
The issue is that, even with Percentage Scoring on, the Tier given is not the right one. I might end up doing a fixed scoring tier system instead of using StepMania's own.

Edit: Alright, made the new system, it actually works quite fine. I'll push it after polishing it.

**Comment by JoseVarelaP** [comment]
New system now functions perfectly and is now pushed.

![captura de pantalla 2018-10-27 a la s 23 51 07](https://user-images.githubusercontent.com/23246027/47612280-93ad3200-da45-11e8-9994-8f1e4269634d.png)
