### ISSUE TITLE
ScreenAdvertisement does not end on its own

### ISSUE THREAD

**Issue by SheepyChris** [JoseVarelaP/In-The-Groove2-SM5#4]
The ITG PS2 advertisement screen during attract mode runs indefinitely until a player joins the game. Happens with all modes, including Pay.

**Comment by JoseVarelaP** [comment]
Checked and yeah, it goes infinitely Just fixed it with a 6 second timer.

**Comment by SheepyChris** [comment]
OpenITG utilizes 10 seconds for the screen iirc.

**Comment by JoseVarelaP** [comment]
ah whoops, then i'll deal with that.
